# Generated by Django 3.2.4 on 2021-06-04 05:38

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='FridgeItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('quantity', models.IntegerField()),
                ('units', models.CharField(max_length=200)),
                ('expirationDate', models.DateTimeField(verbose_name='expiration date')),
            ],
        ),
    ]
